[build]
  base = "web/"
  command = "npm run build"
  publish = "/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
 from = "https://cms.swipestation.co.uk/*"
 to = "https://swipestation.sanity.studio/:splat"
 status = 200
 force = true # COMMENT: ensure that we always redirect
 headers = {X-From = "Netlify"}



[[redirects]]
 from = "https://preview.swipestation.co.uk/*"
 to = "https://swipestation.herokuapp.com/:splat"
 status = 200
 force = true # COMMENT: ensure that we always redirect
 headers = {X-From = "Netlify"}


[[plugins]]
  package = "netlify-plugin-gatsby-cache"
